root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "cd ./static/content && bunx tailwindcss -i ./../../web/input.css -o ./dist/output.css --watch && cd ./../../ && templ generate && go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[[tasks]]
name = "frontend"
script = "bunx tailwindcss -i ./../../web/input.css -o ./dist/output.css --watch"
cwd = "./static/content"
wait = 1000

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
